# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 70178181838f5c662f15df55cabe709f1efaa412f14a8857d8b54566904513ec3c77ba09f42295226eb13dbc150881e92ceca39131e665309a3b83e90286326c

test:
  secret_key_base: a61c15c2567854b01bb7bd0f8a03cc0ce5a3fc4ebb7f4ca39b235cb2dd6b1bfafc8292d235bdfcadcfbd3ad1457f3d0cc866037177712b3a345e33cc7866810a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
